@startuml
actor Client

node "Frontend" {
    component vuejs
}

node "Raspberry Pi" {
    node Players {
        component mpd
        component raat
        component shairport
        component librespot
        component squeezlite
        component toslink
    }


    node nginx{
        component webserver
        component audiocontrol
        component "config-server" as config
        component sigmatcp
    
        interface ":80" as 80
        interface ":1080" as 1080
        interface ":1081" as 1081
        interface ":13141" as 13141
    
        interface "/api/audiocontrol" as apiaudiocontrol
        interface "/api/config" as apiconfig
        interface "/api/dsptoolkit" as apidsptoolkit
    }
}

node "External" {
    component last.fm
    component spotify
    component musicbrainz
    component theaudiodb
    component fanart.tv
}

80 --> webserver
1080 --> audiocontrol
1081 --> config
13141 --> sigmatcp

apiconfig --> 1081
apiaudiocontrol --> 1080
apidsptoolkit --> 13141

audiocontrol --> mpd
audiocontrol --> raat
audiocontrol --> shairport
audiocontrol --> librespot
audiocontrol --> squeezlite
audiocontrol --> toslink

Client --> vuejs
vuejs --> 80
vuejs --> apiaudiocontrol
vuejs --> apiconfig
vuejs --> apidsptoolkit
vuejs --> last.fm
vuejs --> spotify
vuejs --> musicbrainz
vuejs --> theaudiodb
vuejs --> fanart.tv
@enduml
